# Config file pilatus-persister

radio:
    # Usually doesn't need to be changed
    url: https://radio.radiopilatus.ch/api/pub/gql/radiopilatus/AudioLiveData/e8ed774ebb6a811303ea3ff7078581730ff3914c

    # Usually doesn't need to be changed
    timezone: Europe/Zurich

db:
    # Specify an IP-address or a domain
    host: localhost

    # Default port is 3306
    port: 3306

    # Credentials for accessing the database server
    user: root
    passwd: my-secret-password

    # Specify the name of the database and the table where the data should be saved to
    db: my-db-name
    table: my-table-name
