# radiostation-persister config

radio:
    # Specify valid URL to the JSON-file (this example uses Radio Pilatus)
    url: https://radio.radiopilatus.ch/api/pub/gql/radiopilatus/AudioLiveData/e8ed774ebb6a811303ea3ff7078581730ff3914c

    # Specify the timezone (keep Europe/Zurich if you are using it for Swiss radio stations)
    timezone: Europe/Zurich

db:
    # Specify an IP-address or a domain
    host: localhost

    # Specify the port of the database server (default for MySQL is 3306)
    port: 3306

    # Specify the credentials for accessing the database server
    user: root
    passwd: my-secret-password

    # Specify the name of the database and the table where the data should be saved to
    db: my-db-name
    table: my-table-name
